/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts,scss}'
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design tokens
        'primary':                    '#e6c487',
        'primary-fixed':              '#ffdea4',
        'primary-fixed-dim':          '#e4c285',
        'on-primary':                 '#412d00',
        'on-primary-fixed':           '#261900',
        'on-primary-fixed-variant':   '#5a4312',
        'primary-container':          '#c9a96e',
        'on-primary-container':       '#543d0c',
        'inverse-primary':            '#745a27',
        'secondary':                  '#ffb4a4',
        'secondary-fixed':            '#ffdad3',
        'secondary-fixed-dim':        '#ffb4a4',
        'on-secondary':               '#5e1708',
        'on-secondary-fixed':         '#3e0500',
        'on-secondary-fixed-variant': '#7c2d1c',
        'secondary-container':        '#7f2f1e',
        'on-secondary-container':     '#ff9f8a',
        'tertiary':                   '#c9c8c8',
        'tertiary-fixed':             '#e3e2e2',
        'tertiary-fixed-dim':         '#c7c6c6',
        'on-tertiary':                '#303031',
        'on-tertiary-fixed':          '#1b1c1c',
        'on-tertiary-fixed-variant':  '#464747',
        'tertiary-container':         '#aeadad',
        'on-tertiary-container':      '#404141',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'background':                 '#131313',
        'on-background':              '#e5e2e1',
        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#3a3939',
        'surface-tint':               '#e4c285',
        'surface-variant':            '#353534',
        'on-surface':                 '#e5e2e1',
        'on-surface-variant':         '#d0c5b5',
        'inverse-surface':            '#e5e2e1',
        'inverse-on-surface':         '#313030',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1c1b1b',
        'surface-container':          '#201f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353534',
        'outline':                    '#998f81',
        'outline-variant':            '#4d463a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body:     ['"Inter"', 'sans-serif'],
        label:    ['"Inter"', 'sans-serif'],
      },
    },
  },
  safelist: [
    'bg-background/60',
    'bg-background',
    'border-b',
    'border-outline-variant',
  ],
  plugins: [],
};
